# Generated by Django 3.2.8 on 2021-10-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], max_length=11)),
                ('superstructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.superstructure')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('CPF', models.CharField(max_length=11)),
                ('schedule', models.ManyToManyField(to='core.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ManyToManyField(to='core.Host')),
            ],
        ),
    ]
