# Generated by Django 3.2.8 on 2021-10-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211026_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='event',
        ),
        migrations.AddField(
            model_name='host',
            name='event',
            field=models.ManyToManyField(to='core.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], max_length=11),
        ),
    ]
